Fix NoSuchMethodError mini inapp crash
Fragment.getContext() is only supported at API level 23 - changing to getActivity() will resolve.

Issue not caught initially due to build tools error.